### ISSUE TITLE
Add role to MooseOppai

### ISSUE THREAD

**Issue by MooseOppai** [JoeBiller/Group_6#6]
give person the database role.

**Comment by JoeBiller** [comment]
Comment for TA: In retrospect, I should have made everyone use the `@username` naming scheme so that everything is consistent. I take the blame as team leader for not having this be made clear ahead of time. I will make sure to inform them about this promptly so that all future issues and commits are consistent.

This issue involves @MooseOppai.

**Comment by MooseOppai** [comment]
fixed in pull request #9
