### ISSUE TITLE
Add Role to mitchjtoth

### ISSUE THREAD

**Issue by mitchjtoth** [JoeBiller/Group_6#7]
Give mitchjtoth the Frontend role.

**Comment by mitchjtoth** [comment]
Fixed in pull request #10

**Comment by JoeBiller** [comment]
Comment for TA: In retrospect, I should have made everyone use the `@username` naming scheme so that everything is consistent. I take the blame as team leader for not having this be made clear ahead of time. I will make sure to inform them about this promptly so that all future issues and commits are consistent.

This issue involves @mitchjtoth.
