### ISSUE TITLE
Add role to Mak0918

### ISSUE THREAD

**Issue by Mak0918** [JoeBiller/Group_6#8]
Give Mak0918 the Backend role.

**Comment by Mak0918** [comment]
Fixed in pull request #11

**Comment by JoeBiller** [comment]
Comment for TA: In retrospect, I should have made everyone use the `@username` naming scheme so that everything is consistent. I take the blame as team leader for not having this be made clear ahead of time. I will make sure to inform them about this promptly so that all future issues and commits are consistent.

This issue involves @Mak0918.
